### ISSUE TITLE
I see nothing opening the page

### ISSUE THREAD

**Issue by leolle** [RickyCordero/d3-force-graph-flask#1]
I see nothing on the page when I click any of the contents from the entrance.

**Comment by RickyCordero** [comment]
Hmm, maybe it's a package issue in the server code. I just pushed the requirements.txt file for my environment (which uses networkx 2.3) so try creating that environment. I can see the graphs on multiple browsers so it's probably not a client issue. Also, make sure graph.json is in static/json/

**Comment by leolle** [comment]
Thank you.
It works after I update my libs.

BTW, I am new to D3 and JavaScript, do I just need to modify the app.py code to create a new static/json/graph.json file if I need to create a new graph with my own data?

I don't see any methods to read the graph.json file from your code.

**Comment by RickyCordero** [comment]
D3 can load json data from the client side via d3.json(~, ) where ~ can be the location of the data on the file server, e.g. static/json/ (arbitrary choice) or from an API route like /data, the one created by us in app.py with flask. In this code, we create a random graph from the server, turn it into json, format the json for d3 visualization, then serve the json to the client in those two ways. Just pushed an update with some comments in app.py and each js file which should clarify 👍
